# Generated by Django 6.0.3 on 2026-03-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_rename_nodemodule_to_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentInfoFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='联系电话')),
                ('current_community', models.CharField(blank=True, max_length=200, verbose_name='现住小区/建筑')),
                ('current_door', models.CharField(blank=True, max_length=100, verbose_name='门牌地址')),
                ('is_key_person', models.BooleanField(default=False, verbose_name='是否重点人员')),
                ('registered_community', models.CharField(blank=True, max_length=200, verbose_name='户籍小区/建筑')),
                ('registered_address', models.CharField(blank=True, max_length=200, verbose_name='户籍地址')),
                ('registered_region', models.JSONField(blank=True, null=True, verbose_name='户籍地址省市区')),
                ('household_number', models.CharField(blank=True, max_length=50, verbose_name='户编号')),
                ('is_separated', models.BooleanField(default=False, verbose_name='是否人户分离')),
                ('actual_residence', models.CharField(blank=True, max_length=200, verbose_name='实际居住地')),
                ('is_moved_out', models.BooleanField(default=False, verbose_name='是否已迁出')),
                ('move_out_date', models.DateField(blank=True, null=True, verbose_name='迁出日期')),
                ('move_to_place', models.CharField(blank=True, max_length=200, verbose_name='迁往地')),
                ('is_deceased', models.BooleanField(default=False, verbose_name='是否已死亡')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='死亡日期')),
                ('work_status', models.CharField(blank=True, max_length=50, verbose_name='工作学习情况')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_residents', to='core.taxonomyitem', verbose_name='文化程度')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_residents', to='core.taxonomyitem', verbose_name='性别')),
                ('grid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grid_residents', to='core.taxonomyitem', verbose_name='所属网格')),
                ('health_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_status_residents', to='core.taxonomyitem', verbose_name='健康状况')),
                ('key_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_category_residents', to='core.taxonomyitem', verbose_name='重点类别')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marital_status_residents', to='core.taxonomyitem', verbose_name='婚姻状况')),
                ('nation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nation_residents', to='core.taxonomyitem', verbose_name='民族')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_info_fields', to='core.node', verbose_name='关联节点')),
                ('political_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='political_status_residents', to='core.taxonomyitem', verbose_name='政治面貌')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_relation_residents', to='core.taxonomyitem', verbose_name='与其他人员关系')),
                ('resident_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_type_residents', to='core.taxonomyitem', verbose_name='人员类型')),
            ],
            options={
                'verbose_name': '居民',
                'verbose_name_plural': '居民',
                'db_table': 'resident_info_fields',
            },
        ),
    ]
