# Generated by Django 6.0.3 on 2026-03-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfields',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='领英'),
        ),
    ]
