# Generated by Django 6.0.3 on 2026-03-15 04:56
# Merged migrations: 0001 + 0002 + 0003 + 0004 + 0005 + 0008 + 0003_add_navigation_cards

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='配置键名（唯一，例如 "upload_max_size_mb"）', max_length=128, unique=True, verbose_name='配置键')),
                ('value', models.TextField(help_text='配置值（统一存字符串，服务层负责类型转换）', verbose_name='配置值')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='词汇表名称')),
                ('slug', models.CharField(db_index=True, help_text='URL 标识', max_length=128, unique=True, verbose_name='标识符')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '词汇表',
                'verbose_name_plural': '词汇表',
                'db_table': 'taxonomies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, help_text='显示昵称（仪表盘、项目成员列表等处优先显示）', max_length=64, null=True, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, help_text='用户邮箱（可选，用于密码重置、通知等）', max_length=254, null=True, verbose_name='邮箱')),
                ('is_admin', models.BooleanField(default=False, help_text='是否为系统管理员（拥有后台管理权限）', verbose_name='系统管理员')),
                ('role', models.CharField(choices=[('manager', '一类用户'), ('leader', '二类用户'), ('employee', '三类用户')], default='employee', help_text='角色：manager=一类用户 / leader=二类用户 / employee=三类用户', max_length=20, verbose_name='角色')),
                ('permissions', models.JSONField(default=list, help_text='细粒度权限列表，如 ["system.manage", "user.manage"]', verbose_name='权限列表')),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='连续登录失败次数，达到阈值后临时锁定', verbose_name='登录失败次数')),
                ('locked_until', models.DateTimeField(blank=True, help_text='账号临时锁定的截止时间（为空表示未锁定）', null=True, verbose_name='锁定截止时间')),
                ('theme', models.CharField(choices=[('default', '默认'), ('gov', '政府风格'), ('indigo', '靛蓝风格'), ('dopamine', '多巴胺'), ('macaron', '马卡龙'), ('teal', '深绿'), ('uniklo', 'uniKLO')], default='default', max_length=20, verbose_name='界面主题')),
                ('notifications_enabled', models.BooleanField(default=True, help_text='是否开启系统通知（新项目、任务提醒等）', verbose_name='开启通知')),
                ('preferred_language', models.CharField(default='zh', help_text='首选界面语言：zh / en', max_length=10, verbose_name='首选语言')),
                ('navigation_cards', models.JSONField(blank=True, default=list, help_text='用户自定义导航卡片，存储为JSON数组', verbose_name='导航卡片配置')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TaxonomyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='词汇名称')),
                ('description', models.CharField(blank=True, max_length=512, null=True, verbose_name='描述')),
                ('weight', models.IntegerField(default=0, verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.taxonomy', verbose_name='所属词汇表')),
            ],
            options={
                'verbose_name': '词汇项',
                'verbose_name_plural': '词汇项',
                'db_table': 'taxonomy_items',
                'ordering': ['weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChinaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='行政区划代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('level', models.IntegerField(choices=[(1, '省级'), (2, '地级市'), (3, '县/区')], verbose_name='层级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.chinaregion', verbose_name='父级行政区划')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'db_table': 'china_regions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点类型名称')),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='标识符')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('icon', models.CharField(default='bi-folder', max_length=50, verbose_name='图标')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('fields_config', models.JSONField(default=list, verbose_name='字段配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '节点类型',
                'verbose_name_plural': '节点类型',
                'db_table': 'node_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nodes', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.nodetype', verbose_name='节点类型')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'db_table': 'nodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
