# Generated by Django 6.0.3 on 2026-03-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', '一类用户'), ('leader', '二类用户'), ('employee', '三类用户')], default='employee', help_text='角色：manager=一类用户 / leader=二类用户 / employee=三类用户', max_length=20, verbose_name='角色'),
        ),
    ]
