# Generated by Django 6.0.3 on 2026-03-25 06:09
# Module system - independent from node system

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=50, unique=True, verbose_name='模块ID')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('path', models.CharField(max_length=200, verbose_name='模块路径')),
                ('is_installed', models.BooleanField(default=False, verbose_name='是否已安装')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否启用')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统默认模块')),
                ('module_type', models.CharField(default='node', max_length=20, verbose_name='模块类型')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='安装时间')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='启用时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'db_table': 'modules',
                'ordering': ['name'],
            },
        ),
    ]
