# Generated by Django 6.0.3 on 2026-04-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='工具名称')),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='标识符')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('icon', models.CharField(default='bi-wrench', max_length=50, verbose_name='图标')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具类型',
                'verbose_name_plural': '工具类型',
                'db_table': 'tool_types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='navigation_cards',
            field=models.JSONField(blank=True, default=list, help_text='用户自定义导航卡片，存储为JSON数组，每张卡片包含position字段(1-12)', verbose_name='导航卡片配置'),
        ),
    ]
