# Generated by Django 6.0.3 on 2026-03-17 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='行政区划代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('level', models.IntegerField(choices=[(1, '省级'), (2, '地级市'), (3, '县/区')], verbose_name='层级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.chinaregion', verbose_name='父级行政区划')),
            ],
            options={
                'verbose_name': '行政区划',
                'verbose_name_plural': '行政区划',
                'db_table': 'china_regions',
                'ordering': ['code'],
            },
        ),
    ]
