# Generated by Django 6.0 on 2026-03-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chinaregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', '默认'), ('gov', '政府风格'), ('indigo', '靛蓝风格'), ('dopamine', '多巴胺'), ('macaron', '马卡龙'), ('teal', '深绿'), ('uniklo', 'uniKLO')], default='default', max_length=20, verbose_name='界面主题'),
        ),
    ]
