# Generated by Django 6.0.3 on 2026-03-24 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点类型名称')),
                ('slug', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='标识符')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='描述')),
                ('icon', models.CharField(default='bi-folder', max_length=50, verbose_name='图标')),
                ('fields_config', models.JSONField(default=list, verbose_name='字段配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '节点类型',
                'verbose_name_plural': '节点类型',
                'db_table': 'node_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nodes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_nodes', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.nodetype', verbose_name='节点类型')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
                'db_table': 'nodes',
                'ordering': ['-created_at'],
            },
        ),
    ]
