# Generated by Django 6.0.3 on 2026-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_import_china_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='install_on_init',
            field=models.BooleanField(default=True, verbose_name='初始化时安装'),
        ),
    ]
