# Generated by Django 6.0.3 on 2026-05-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_install_on_init_to_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(default='bi-wrench', max_length=50, verbose_name='图标'),
        ),
    ]
