# Generated by Django 6.0.3 on 2026-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nodemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetype',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者'),
        ),
    ]
