# Generated by Django 6.0.4 on 2026-05-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_icon_to_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_type',
            field=models.CharField(choices=[('node', '节点模块'), ('system', '系统模块'), ('tool', '工具模块')], default='node', max_length=20, verbose_name='模块类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', '默认'), ('gov', '政府风格'), ('indigo', '靛蓝风格'), ('dopamine', '多巴胺风格'), ('macaron', '马卡龙风格'), ('teal', '青绿风格'), ('uniklo', '极简风格')], default='default', max_length=20, verbose_name='界面主题'),
        ),
    ]
