# Generated by Django 6.0.3 on 2026-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nodetype_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodemodule',
            name='module_type',
            field=models.CharField(default='node', max_length=20, verbose_name='模块类型'),
        ),
    ]
