# Generated by Django 6.0.3 on 2026-03-29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_module_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NodeModule',
            new_name='Module',
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['name'], 'verbose_name': '模块', 'verbose_name_plural': '模块'},
        ),
        migrations.AlterModelTable(
            name='module',
            table='modules',
        ),
    ]