# -*- coding: utf-8 -*-
"""
国内客户样本数据
"""

DOMESTIC_CUSTOMERS = [
    {
        'customer_name': '张伟',
        'customer_code': 'DC001',
        'enterprise_name': '深圳市华腾科技有限公司',
        'phone1': '0755-86521234',
        'email1': 'zhangwei@huateng-tech.cn',
        'phone2': '0755-86521235',
        'email2': 'support@huateng-tech.cn',
        'address': '南山区科技园南区高新南七道',
        'postal_code': '518057',
        'region': {'province': '广东省', 'city': '深圳市', 'district': '南山区'},
        'industry': '科技服务',
        'registered_capital': 50000000.00,
        'credit_limit': 5000000.00,
        'wechat': 'huatengtech',
        'dingtalk': 'huateng001',
        'website': 'https://www.huateng-tech.cn',
        'notes': 'VIP客户，月订单量超过50万，合作超过5年',
    },
    {
        'customer_name': '李娜',
        'customer_code': 'DC002',
        'enterprise_name': '杭州云栖数据有限公司',
        'phone1': '0571-87654321',
        'email1': 'lina@yunqidata.com',
        'address': '西湖区文三路478号华星时代广场',
        'postal_code': '310012',
        'region': {'province': '浙江省', 'city': '杭州市', 'district': '西湖区'},
        'industry': '信息技术',
        'registered_capital': 30000000.00,
        'credit_limit': 3000000.00,
        'wechat': 'yunqidata',
        'dingtalk': 'yunqi2024',
        'website': 'https://www.yunqidata.com',
        'notes': '阿里系合作伙伴，大数据解决方案提供商',
    },
    {
        'customer_name': '王建国',
        'customer_code': 'DC003',
        'enterprise_name': '北京中科智远信息技术股份有限公司',
        'phone1': '010-82345678',
        'email1': 'wangjianguo@zkzytech.cn',
        'phone2': '010-82345679',
        'email2': 'sales@zkzytech.cn',
        'address': '海淀区中关村大街1号',
        'postal_code': '100084',
        'region': {'province': '北京市', 'city': '北京市', 'district': '海淀区'},
        'industry': '人工智能',
        'registered_capital': 100000000.00,
        'credit_limit': 10000000.00,
        'wechat': 'zkzytech',
        'dingtalk': 'zkzy2024',
        'website': 'https://www.zkzytech.cn',
        'notes': '上市公司，AI领域龙头，年采购额超千万',
    },
    {
        'customer_name': '陈明',
        'customer_code': 'DC004',
        'enterprise_name': '上海锦程国际物流有限公司',
        'phone1': '021-58881234',
        'email1': 'chenming@jclogistics.cn',
        'address': '浦东新区陆家嘴环路1000号',
        'postal_code': '200120',
        'region': {'province': '上海市', 'city': '上海市', 'district': '浦东新区'},
        'industry': '物流运输',
        'registered_capital': 20000000.00,
        'credit_limit': 2000000.00,
        'wechat': 'jclogistics',
        'dingtalk': 'jcwl123',
        'website': 'https://www.jclogistics.cn',
        'notes': '国际物流龙头企业，跨境电商合作方',
    },
    {
        'customer_name': '刘洋',
        'customer_code': 'DC005',
        'enterprise_name': '广州白云电器设备有限公司',
        'phone1': '020-86541234',
        'email1': 'liuyang@bypower.cn',
        'address': '白云区机场路168号',
        'postal_code': '510403',
        'region': {'province': '广东省', 'city': '广州市', 'district': '白云区'},
        'industry': '制造业',
        'registered_capital': 15000000.00,
        'credit_limit': 1500000.00,
        'wechat': 'bypower123',
        'dingtalk': 'bypower2024',
        'website': 'https://www.bypower.cn',
        'notes': '电器设备制造商，稳定合作3年',
    },
    {
        'customer_name': '赵敏',
        'customer_code': 'DC006',
        'enterprise_name': '成都天府智能科技有限公司',
        'phone1': '028-87654321',
        'email1': 'zhaomin@tianfuzhineng.cn',
        'address': '高新区天府大道中段666号',
        'postal_code': '610041',
        'region': {'province': '四川省', 'city': '成都市', 'district': '高新区'},
        'industry': '智能制造',
        'registered_capital': 8000000.00,
        'credit_limit': 800000.00,
        'wechat': 'tianfuzhineng',
        'dingtalk': 'tfzn2024',
        'website': 'https://www.tianfuzhineng.cn',
        'notes': '成都智能制造示范企业',
    },
    {
        'customer_name': '周杰',
        'customer_code': 'DC007',
        'enterprise_name': '南京苏雅环保科技有限公司',
        'phone1': '025-84561234',
        'email1': 'zhoujie@suyahb.cn',
        'address': '江宁区将军大道100号',
        'postal_code': '211100',
        'region': {'province': '江苏省', 'city': '南京市', 'district': '江宁区'},
        'industry': '环保科技',
        'registered_capital': 5000000.00,
        'credit_limit': 500000.00,
        'wechat': 'suyahuanbao',
        'dingtalk': 'suya001',
        'website': 'https://www.suyahb.cn',
        'notes': '潜在客户，正在洽谈中，预计下季度签约',
    },
    {
        'customer_name': '吴昊',
        'customer_code': 'DC008',
        'enterprise_name': '武汉光谷联合创新有限公司',
        'phone1': '027-81234567',
        'email1': 'wuhao@guangguunion.cn',
        'address': '东湖高新区光谷大道77号',
        'postal_code': '430074',
        'region': {'province': '湖北省', 'city': '武汉市', 'district': '东湖高新区'},
        'industry': '光电技术',
        'registered_capital': 12000000.00,
        'credit_limit': 1200000.00,
        'wechat': 'guangguunion',
        'dingtalk': 'ggunion2024',
        'website': 'https://www.guangguunion.cn',
        'notes': '光谷地区知名企业，光电技术领先',
    },
    {
        'customer_name': '郑强',
        'customer_code': 'DC009',
        'enterprise_name': '西安华秦精密机械有限公司',
        'phone1': '029-86543210',
        'email1': 'zhengqiang@huaqinprecision.cn',
        'address': '经济技术开发区凤城十路',
        'postal_code': '710018',
        'region': {'province': '陕西省', 'city': '西安市', 'district': '经开区'},
        'industry': '精密制造',
        'registered_capital': 6000000.00,
        'credit_limit': 600000.00,
        'wechat': 'huaqinjm',
        'dingtalk': 'hqjm2024',
        'website': 'https://www.huaqinprecision.cn',
        'notes': '精密机械制造商，军工认证企业',
    },
    {
        'customer_name': '孙丽',
        'customer_code': 'DC010',
        'enterprise_name': '天津滨海新区新能源有限公司',
        'phone1': '022-65881234',
        'email1': 'sunli@tianjinenergy.cn',
        'phone2': '022-65881235',
        'email2': 'sales@tianjinenergy.cn',
        'address': '滨海新区第五大街100号',
        'postal_code': '300450',
        'region': {'province': '天津市', 'city': '天津市', 'district': '滨海新区'},
        'industry': '新能源',
        'registered_capital': 80000000.00,
        'credit_limit': 8000000.00,
        'wechat': 'tianjinenergy',
        'dingtalk': 'tjny2024',
        'website': 'https://www.tianjinenergy.cn',
        'notes': '国企背景，新能源行业领军企业',
    },
    {
        'customer_name': '黄磊',
        'customer_code': 'DC011',
        'enterprise_name': '苏州工业园区智造创新有限公司',
        'phone1': '0512-62581234',
        'email1': 'huanglei@szindustrialpark.cn',
        'address': '工业园区星湖街328号',
        'postal_code': '215028',
        'region': {'province': '江苏省', 'city': '苏州市', 'district': '工业园区'},
        'industry': '智能制造',
        'registered_capital': 10000000.00,
        'credit_limit': 1000000.00,
        'wechat': 'szzhinzao',
        'dingtalk': 'zzcx2024',
        'website': 'https://www.szindustrialpark.cn',
        'notes': '苏州工业园区标杆企业',
    },
    {
        'customer_name': '林峰',
        'customer_code': 'DC012',
        'enterprise_name': '重庆两江新区大数据有限公司',
        'phone1': '023-67681234',
        'email1': 'linfeng@cqljdata.cn',
        'address': '两江新区金开大道龙晴路',
        'postal_code': '401121',
        'region': {'province': '重庆市', 'city': '重庆市', 'district': '两江新区'},
        'industry': '大数据',
        'registered_capital': 15000000.00,
        'credit_limit': 1500000.00,
        'wechat': 'cqljdata',
        'dingtalk': 'ljdata2024',
        'website': 'https://www.cqljdata.cn',
        'notes': '重庆大数据试点企业，政府合作项目',
    },
    {
        'customer_name': '马超',
        'customer_code': 'DC013',
        'enterprise_name': '青岛海尔智家股份有限公司',
        'phone1': '0532-87651234',
        'email1': 'machao@haier-smart.cn',
        'phone2': '0532-87651235',
        'email2': 'service@haier-smart.cn',
        'address': '崂山区海尔路1号',
        'postal_code': '266101',
        'region': {'province': '山东省', 'city': '青岛市', 'district': '崂山区'},
        'industry': '智能家居',
        'registered_capital': 500000000.00,
        'credit_limit': 50000000.00,
        'wechat': 'haiersmart',
        'dingtalk': 'haier001',
        'website': 'https://www.haier-smart.cn',
        'notes': '上市公司，智能家居行业龙头，年采购额超千万',
    },
    {
        'customer_name': '杨帆',
        'customer_code': 'DC014',
        'enterprise_name': '长沙高新区人工智能创新有限公司',
        'phone1': '0731-89781234',
        'email1': 'yangfan@csaiinno.cn',
        'address': '高新区麓谷大道168号',
        'postal_code': '410205',
        'region': {'province': '湖南省', 'city': '长沙市', 'district': '高新区'},
        'industry': '人工智能',
        'registered_capital': 4000000.00,
        'credit_limit': 400000.00,
        'wechat': 'csaiinno',
        'dingtalk': 'csai2024',
        'website': 'https://www.csaiinno.cn',
        'notes': '潜在客户，AI初创公司，正在进行商务洽谈',
    },
    {
        'customer_name': '徐婷',
        'customer_code': 'DC015',
        'enterprise_name': '郑州航空港区国际贸易有限公司',
        'phone1': '0371-56881234',
        'email1': 'xuting@zzairport.cn',
        'address': '航空港区综合保税区',
        'postal_code': '451161',
        'region': {'province': '河南省', 'city': '郑州市', 'district': '航空港区'},
        'industry': '国际贸易',
        'registered_capital': 10000000.00,
        'credit_limit': 1000000.00,
        'wechat': 'zzairtrade',
        'dingtalk': 'zztrade2024',
        'website': 'https://www.zzairport.cn',
        'notes': '郑州航空港区重点扶持企业',
    },
    {
        'customer_name': '许刚',
        'customer_code': 'DC016',
        'enterprise_name': '福州马尾经济开发区实业集团',
        'phone1': '0591-83681234',
        'email1': 'xugang@fzmawei.cn',
        'address': '马尾区罗星西路88号',
        'postal_code': '350015',
        'region': {'province': '福建省', 'city': '福州市', 'district': '马尾区'},
        'industry': '综合实业',
        'registered_capital': 20000000.00,
        'credit_limit': 2000000.00,
        'wechat': 'fzmawei',
        'dingtalk': 'mwgroup2024',
        'website': 'https://www.fzmawei.cn',
        'notes': '马尾区国有企业集团，多元化经营',
    },
    {
        'customer_name': '韩冰',
        'customer_code': 'DC017',
        'enterprise_name': '沈阳浑南新区智能制造有限公司',
        'phone1': '024-24681234',
        'email1': 'hanbing@syhunnuan.cn',
        'address': '浑南区创新路200号',
        'postal_code': '110169',
        'region': {'province': '辽宁省', 'city': '沈阳市', 'district': '浑南区'},
        'industry': '智能制造',
        'registered_capital': 6000000.00,
        'credit_limit': 600000.00,
        'wechat': 'syhunnuan',
        'dingtalk': 'syzn2024',
        'website': 'https://www.syhunnuan.cn',
        'notes': '潜在客户，东三省智能制造试点企业',
    },
    {
        'customer_name': '曹阳',
        'customer_code': 'DC018',
        'enterprise_name': '东莞松山湖材料科技有限公司',
        'phone1': '0769-26881234',
        'email1': 'caoyang@dgssl.cn',
        'address': '松山湖高新技术产业开发区工业西路',
        'postal_code': '523808',
        'region': {'province': '广东省', 'city': '东莞市', 'district': '松山湖'},
        'industry': '新材料',
        'registered_capital': 12000000.00,
        'credit_limit': 1200000.00,
        'wechat': 'dgmaterial',
        'dingtalk': 'sslmaterial',
        'website': 'https://www.dgssl.cn',
        'notes': '松山湖高新技术企业，新材料研发',
    },
    {
        'customer_name': '彭涛',
        'customer_code': 'DC019',
        'enterprise_name': '南昌高新区创新创业有限公司',
        'phone1': '0791-88671234',
        'email1': 'pengtao@nanchanginno.cn',
        'address': '高新区京东大道399号',
        'postal_code': '330096',
        'region': {'province': '江西省', 'city': '南昌市', 'district': '高新区'},
        'industry': '创新创业服务',
        'registered_capital': 3000000.00,
        'credit_limit': 300000.00,
        'wechat': 'nanchanginno',
        'dingtalk': 'ncchuangye',
        'website': 'https://www.nanchanginno.cn',
        'notes': '潜在客户，创业孵化平台，正在对接资源合作',
    },
    {
        'customer_name': '唐静',
        'customer_code': 'DC020',
        'enterprise_name': '石家庄正定新区数字经济有限公司',
        'phone1': '0311-86781234',
        'email1': 'tangjing@szdzkj.cn',
        'address': '正定新区隆兴路168号',
        'postal_code': '050899',
        'region': {'province': '河北省', 'city': '石家庄市', 'district': '正定新区'},
        'industry': '数字经济',
        'registered_capital': 8000000.00,
        'credit_limit': 800000.00,
        'wechat': 'szdzkj',
        'dingtalk': 'szdz2024',
        'website': 'https://www.szdzkj.cn',
        'notes': '正定新区数字经济示范企业',
    },
]
