# Generated by Django 6.0.3 on 2026-04-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='发件人')),
                ('to_email', models.EmailField(max_length=254, verbose_name='收件人')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件主题')),
                ('text_body', models.TextField(blank=True, verbose_name='纯文本正文')),
                ('html_body', models.TextField(blank=True, verbose_name='HTML正文')),
                ('template_name', models.CharField(blank=True, max_length=64, verbose_name='使用的模板')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=16, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮件发送记录',
                'verbose_name_plural': '邮件发送记录',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模板标识')),
                ('subject', models.CharField(max_length=255, verbose_name='邮件主题模板')),
                ('html_body', models.TextField(verbose_name='HTML正文模板')),
                ('text_body', models.TextField(blank=True, verbose_name='纯文本正文模板')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='模板说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'db_table': 'email_templates',
            },
        ),
    ]
