# -*- coding: utf-8 -*-
"""
海外客户样本数据
"""

OVERSEAS_CUSTOMERS = [
    {
        'customer_name': 'John Smith',
        'customer_code': 'OC001',
        'enterprise_name': 'ABC Trading Co., Ltd.',
        'phone1': '+1-212-555-0101',
        'email1': 'john.smith@abctrading.com',
        'linkedin': 'https://www.linkedin.com/company/abctrading',
        'province': 'New York',
        'address': '123 Business Ave, Manhattan',
        'postal_code': '10001',
        'industry': 'Import & Export',
        'registered_capital': 5000000.00,
        'credit_limit': 500000.00,
        'website': 'https://www.abctrading.com',
        'notes': 'Long-term partner, reliable payment history',
    },
    {
        'customer_name': 'Hans Mueller',
        'customer_code': 'OC002',
        'enterprise_name': 'European Imports GmbH',
        'phone1': '+49-30-1234567',
        'email1': 'hans.mueller@european-imports.de',
        'province': 'Berlin',
        'address': 'Friedrichstraße 123',
        'postal_code': '10117',
        'industry': 'Wholesale',
        'registered_capital': 2000000.00,
        'credit_limit': 200000.00,
        'website': 'https://www.european-imports.de',
        'notes': 'German distributor for Asian products',
    },
    {
        'customer_name': 'Emily Watson',
        'customer_code': 'OC003',
        'enterprise_name': 'Sunrise Electronics Ltd.',
        'phone1': '+44-20-7946-0958',
        'email1': 'emily.watson@sunrise-elec.co.uk',
        'phone2': '+44-20-7946-0959',
        'email2': 'support@sunrise-elec.co.uk',
        'linkedin': 'https://www.linkedin.com/company/sunrise-electronics',
        'province': 'London',
        'address': '45 Oxford Street',
        'postal_code': 'W1D 2BS',
        'industry': 'Electronics',
        'registered_capital': 10000000.00,
        'credit_limit': 1000000.00,
        'website': 'https://www.sunrise-elec.co.uk',
        'notes': 'VIP client, quarterly orders exceeding $200K',
    },
    {
        'customer_name': 'Takeshi Yamamoto',
        'customer_code': 'OC004',
        'enterprise_name': 'Tokyo Tech Solutions Inc.',
        'phone1': '+81-3-1234-5678',
        'email1': 'takeshi.yamamoto@tokyotech.jp',
        'province': 'Tokyo',
        'address': '1-1-1 Shibuya, Shibuya-ku',
        'postal_code': '150-0002',
        'industry': 'Technology',
        'registered_capital': 8000000.00,
        'credit_limit': 800000.00,
        'website': 'https://www.tokyotech.jp',
        'notes': 'Technology solutions provider, interested in AI products',
    },
    {
        'customer_name': 'Carlos Rodriguez',
        'customer_code': 'OC005',
        'enterprise_name': 'Mediterranean Trade Corporation',
        'phone1': '+34-91-123-4567',
        'email1': 'carlos.rodriguez@medtrade.es',
        'province': 'Madrid',
        'address': 'Calle Gran Via 28',
        'postal_code': '28013',
        'industry': 'Import & Export',
        'registered_capital': 3000000.00,
        'credit_limit': 300000.00,
        'website': 'https://www.medtrade.es',
        'notes': 'Spanish trade company, specializes in food imports',
    },
    {
        'customer_name': 'Anna Olsen',
        'customer_code': 'OC006',
        'enterprise_name': 'Nordic Solutions AS',
        'phone1': '+47-22-11-22-33',
        'email1': 'anna.olsen@nordicsolutions.no',
        'province': 'Oslo',
        'address': 'Karl Johans gate 15',
        'postal_code': '0159',
        'industry': 'Consulting',
        'registered_capital': 1000000.00,
        'credit_limit': 100000.00,
        'website': 'https://www.nordicsolutions.no',
        'notes': 'Potential client, in negotiation stage',
    },
    {
        'customer_name': 'Michael Chen',
        'customer_code': 'OC007',
        'enterprise_name': 'Pacific Rim Distributors Pty Ltd',
        'phone1': '+61-2-9876-5432',
        'email1': 'michael.chen@pacificrimdist.com.au',
        'province': 'New South Wales',
        'address': '88 George Street',
        'postal_code': '2000',
        'industry': 'Distribution',
        'registered_capital': 4000000.00,
        'credit_limit': 400000.00,
        'website': 'https://www.pacificrimdist.com.au',
        'notes': 'Australian distributor, expanding to Asian markets',
    },
    {
        'customer_name': 'Sophie Weber',
        'customer_code': 'OC008',
        'enterprise_name': 'Global Pharmaceuticals AG',
        'phone1': '+41-44-123-4567',
        'email1': 'sophie.weber@globalpharma.ch',
        'phone2': '+41-44-123-4568',
        'email2': 'orders@globalpharma.ch',
        'linkedin': 'https://www.linkedin.com/company/globalpharma',
        'province': 'Zurich',
        'address': 'Bahnhofstrasse 100',
        'postal_code': '8001',
        'industry': 'Pharmaceutical',
        'registered_capital': 50000000.00,
        'credit_limit': 5000000.00,
        'website': 'https://www.globalpharma.ch',
        'notes': 'VIP pharmaceutical company, monthly orders exceeding $500K',
    },
    {
        'customer_name': 'Park Ji-hoon',
        'customer_code': 'OC009',
        'enterprise_name': 'Seoul Digital Networks Co., Ltd.',
        'phone1': '+82-2-1234-5678',
        'email1': 'jihoon.park@seouldigital.kr',
        'province': 'Seoul',
        'address': '123 Gangnam-daero, Gangnam-gu',
        'postal_code': '135-100',
        'industry': 'Technology',
        'registered_capital': 6000000.00,
        'credit_limit': 600000.00,
        'website': 'https://www.seouldigital.kr',
        'notes': 'Korean tech company, interested in software partnerships',
    },
    {
        'customer_name': 'Fernanda Silva',
        'customer_code': 'OC010',
        'enterprise_name': 'Sao Paulo Commerce Ltda',
        'phone1': '+55-11-3045-6789',
        'email1': 'fernanda.silva@saopaulocomercio.com.br',
        'province': 'São Paulo',
        'address': 'Av. Paulista 1000',
        'postal_code': '01310-100',
        'industry': 'Retail',
        'registered_capital': 1500000.00,
        'credit_limit': 150000.00,
        'website': 'https://www.saopaulocomercio.com.br',
        'notes': 'Brazilian retail company, exploring Asian suppliers',
    },
    {
        'customer_name': 'Pierre Dubois',
        'customer_code': 'OC011',
        'enterprise_name': 'Paris Luxe Imports SARL',
        'phone1': '+33-1-42-60-80-00',
        'email1': 'pierre.dubois@parisluxe.fr',
        'province': 'Île-de-France',
        'address': '168 Rue de Rivoli',
        'postal_code': '75001',
        'industry': 'Luxury Goods',
        'registered_capital': 3000000.00,
        'credit_limit': 300000.00,
        'website': 'https://www.parisluxe.fr',
        'notes': 'French luxury goods importer, specializes in Asian art',
    },
    {
        'customer_name': 'Priya Sharma',
        'customer_code': 'OC012',
        'enterprise_name': 'Mumbai Textiles Company Pvt Ltd',
        'phone1': '+91-22-2201-1234',
        'email1': 'priya.sharma@mumbaistextiles.in',
        'province': 'Maharashtra',
        'address': 'Nariman Point, Fort',
        'postal_code': '400001',
        'industry': 'Textile',
        'registered_capital': 2500000.00,
        'credit_limit': 250000.00,
        'website': 'https://www.mumbaistextiles.in',
        'notes': 'Indian textile exporter, interested in fabric materials',
    },
    {
        'customer_name': 'James Thompson',
        'customer_code': 'OC013',
        'enterprise_name': 'Toronto Business Group Inc.',
        'phone1': '+1-416-555-0123',
        'email1': 'james.thompson@torontobizgroup.ca',
        'province': 'Ontario',
        'address': '100 King Street West',
        'postal_code': 'M5X 1A9',
        'industry': 'Business Services',
        'registered_capital': 2000000.00,
        'credit_limit': 200000.00,
        'website': 'https://www.torontobizgroup.ca',
        'notes': 'Canadian business consulting firm',
    },
    {
        'customer_name': 'Ahmed Al-Rashid',
        'customer_code': 'OC014',
        'enterprise_name': 'Dubai International Trade Hub LLC',
        'phone1': '+971-4-321-1234',
        'email1': 'ahmed.alrashid@dubaitradehub.ae',
        'phone2': '+971-4-321-1235',
        'email2': 'orders@dubaitradehub.ae',
        'linkedin': 'https://www.linkedin.com/company/dubai-trade-hub',
        'province': 'Dubai',
        'address': 'Sheikh Zayed Road, Trade Center 1',
        'postal_code': '0000',
        'industry': 'Import & Export',
        'registered_capital': 15000000.00,
        'credit_limit': 1500000.00,
        'website': 'https://www.dubaitradehub.ae',
        'notes': 'Middle East trade hub, VIP client with high volume',
    },
    {
        'customer_name': 'David Tan',
        'customer_code': 'OC015',
        'enterprise_name': 'Singapore Tech Ventures Pte Ltd',
        'phone1': '+65-6123-4567',
        'email1': 'david.tan@singaporetech.sg',
        'province': 'Central',
        'address': '1 Raffles Place, #20-01',
        'postal_code': '048616',
        'industry': 'Technology',
        'registered_capital': 7000000.00,
        'credit_limit': 700000.00,
        'website': 'https://www.singaporetech.sg',
        'notes': 'Singapore-based tech investment firm',
    },
    {
        'customer_name': 'Maria Garcia',
        'customer_code': 'OC016',
        'enterprise_name': 'Mexico City Imports de CV',
        'phone1': '+52-55-1234-5678',
        'email1': 'maria.garcia@mexicocitiimports.mx',
        'province': 'Ciudad de México',
        'address': 'Paseo de la Reforma 500',
        'postal_code': '06600',
        'industry': 'Import & Export',
        'registered_capital': 1800000.00,
        'credit_limit': 180000.00,
        'website': 'https://www.mexicocitiimports.mx',
        'notes': 'Mexican import company, new partnership',
    },
    {
        'customer_name': 'Jan de Vries',
        'customer_code': 'OC017',
        'enterprise_name': 'Amsterdam Electronics BV',
        'phone1': '+31-20-123-4567',
        'email1': 'jan.devries@amsterdam-elec.nl',
        'province': 'North Holland',
        'address': 'Damrak 100',
        'postal_code': '1012 LX',
        'industry': 'Electronics',
        'registered_capital': 2500000.00,
        'credit_limit': 250000.00,
        'website': 'https://www.amsterdam-elec.nl',
        'notes': 'Dutch electronics distributor',
    },
    {
        'customer_name': 'Somchai Prasert',
        'customer_code': 'OC018',
        'enterprise_name': 'Bangkok Trade Company Limited',
        'phone1': '+66-2-123-4567',
        'email1': 'somchai.prasert@bangkoktrade.co.th',
        'province': 'Bangkok',
        'address': '333 Silom Road, Bang Rak',
        'postal_code': '10500',
        'industry': 'Import & Export',
        'registered_capital': 2000000.00,
        'credit_limit': 200000.00,
        'website': 'https://www.bangkoktrade.co.th',
        'notes': 'Thai trade company, interested in Chinese products',
    },
    {
        'customer_name': 'Wanjiru Kamau',
        'customer_code': 'OC019',
        'enterprise_name': 'Nairobi Agricultural Corporation Ltd',
        'phone1': '+254-20-1234567',
        'email1': 'wanjiru.kamau@nairobiagri.co.ke',
        'province': 'Nairobi County',
        'address': 'Kimathi Street, City Centre',
        'postal_code': '00100',
        'industry': 'Agriculture',
        'registered_capital': 1000000.00,
        'credit_limit': 100000.00,
        'website': 'https://www.nairobiagri.co.ke',
        'notes': 'Kenyan agricultural export company, potential partner',
    },
    {
        'customer_name': 'Erik Lindberg',
        'customer_code': 'OC020',
        'enterprise_name': 'Stockholm Innovations AB',
        'phone1': '+46-8-123 456 78',
        'email1': 'erik.lindberg@stockholminnovations.se',
        'province': 'Stockholm County',
        'address': 'Kungsgatan 44',
        'postal_code': '111 35',
        'industry': 'Innovation & Technology',
        'registered_capital': 3000000.00,
        'credit_limit': 300000.00,
        'website': 'https://www.stockholminnovations.se',
        'notes': 'Swedish innovation company, exploring Asian markets',
    },
]
