# Generated by Django 6.0.3 on 2026-03-24 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_nodetype_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, unique=True, verbose_name='客户名称')),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='客户代码')),
                ('enterprise_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='企业名称')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话1')),
                ('email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话2')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱2')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='省份/城市')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='详细地址')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='邮政编码')),
                ('industry', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属行业')),
                ('registered_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='注册资本')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='信用额度')),
                ('website', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_customers', to='core.taxonomyitem', verbose_name='国家')),
                ('customer_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_level_customers', to='core.taxonomyitem', verbose_name='客户等级')),
                ('customer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_type_customers', to='core.taxonomyitem', verbose_name='客户类型')),
                ('enterprise_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_type_customers', to='core.taxonomyitem', verbose_name='企业性质')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_fields', to='core.node', verbose_name='关联节点')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer_fields',
            },
        ),
    ]
